version: '3.4'

networks:
  web:
    external: true

volumes:
  expensetracker_postgres_data: {}

services:
  expensetrackerapp:
    image: ${DOCKER_REGISTRY-}expensetrackerapp
    build:
      context: .
      dockerfile: ExpenseTrackerApp/Dockerfile
    ports:
      - "8080:8080"  # This ensures port 8080 on your machine maps to the container's port 8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.expensetrackerapp.rule=Host(`doughtrack.com`) || Host(`www.doughtrack.com`)"
      - "traefik.http.routers.expensetrackerapp.entrypoints=web,web-secure"
      - "traefik.http.routers.expensetrackerapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.expensetrackerapp.loadbalancer.server.port=8080"
    depends_on:
      - expensetrackerapp.database
    networks:
      - web

  expensetrackerapp.database:
    image: postgres:latest
    container_name: expensetrackerapp.database
    environment:
      - POSTGRES_DB=expensetrackerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - expensetracker_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - web
