version: '3.4'

services:
  expensetrackerapp:
    image: ${DOCKER_REGISTRY-}expensetrackerapp
    build:
      context: .
      dockerfile: ExpenseTrackerApp/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_HTTPS_PORT=5001
    depends_on:
      - expensetrackerapp.database

  expensetrackerapp.database:
    image: postgres:latest
    container_name: expensetrackerapp.database
    environment:
      - POSTGRES_DB=expensetrackerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/expensetrackerapp-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
